---
# tasks file for zero_footprint_qbittorrent_seedbox/02-qtorrent

- name: QTORRENT | 2.1 Download qBittorrent
  ansible.builtin.get_url:
    url: "{{ qtorrent_url }}"
    dest: "/usr/local/bin/qbittorrent"
    mode: "0755"
  become: true
  tags:
    - qtorrent

- name: QTORRENT | 2.2 Template the configuration for qtorrent
  ansible.builtin.template:
    src: "qbittorrent/qBittorrent.conf.j2"
    dest: "{{ qtorrent_config_file }}"
    backup: true
    mode: "0644"
  tags:
    - qtorrent

- name: QTORRENT | 2.3 Template a service file for qtorrent
  ansible.builtin.template:
    backup: true
    src: "templates/qbittorrent/qtorrent.service.j2"
    dest: "{{ qtorrent_service_file }}"
    mode: "0644"
  become: true
  tags:
    - qtorrent
