---
# handlers file for zero_footprint_qbittorrent_seedbox

# 01-common
- name: Restart tuned
  ansible.builtin.systemd:
    name: "tuned"
    state: "restarted"
  become: true

- name: Restart NetworkManager
  ansible.builtin.systemd:
    name: "NetworkManager"
    state: "restarted"
  become: true

# 02-qbt
- name: Restart qBittorrent
  ansible.builtin.systemd:
    name: "tuned"
    state: "restarted"
  become: true

# 05-security
- name: Reload firewalld
  ansible.builtin.systemd:
    name: "firewalld"
    state: "reloaded"
  become: true

- name: Reload sshd
  ansible.builtin.systemd:
    name: "sshd"
    state: "reloaded"
  become: true

# 06-cleanup
- name: Restart systemd-journald
  ansible.builtin.systemd:
    name: "systemd-journald"
    state: "restarted"
  become: true
